# Generated by Django 4.2.5 on 2023-09-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblogpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='My awesome blog', max_length=255),
        ),
    ]
